services:
  - type: web
    name: qa-insight-backend
    env: python
    region: singapore
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PORT
        value: 8000
    autoDeploy: true
